version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/python:3.7.3
      - image: circleci/node:12.4.0
    steps:
      - checkout
  backend:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - run:
          name: PIP install
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
  frontend:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - run:
          name: NPM install
          command: |
            npm i
      - run:
          name: Build JS
          command: |
            make build
workflows:
  version: 2
  checkout_backend_frontend:
    jobs:
      - checkout_code
      - backend:
          requires:
            - checkout_code
      - frontend:
          requires:
            - checkout_code
